name: render-md-mermaid

on: push

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: render-md-mermaid action
        uses: ./

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '**/*.png **/*.svg'
          commit_message: automatically rendered mermaid diagrams
